baseurl: /Yangxue1988.github.io 

    author :

    name : yangxue

    email : 260712046@qq.com

    github : Yangxue1988

    twitter : username

    feedburner : feedname

permalink: /:categories/:year/:month/:day/:title
